class Tutor {
  Tutor({
    required this.id,
    required this.name,
    required this.subjects,
    required this.hourlyRate,
    required this.mode,
    required this.rating,
    required this.numReviews,
    this.city,
    this.distanceKm,
    this.photoUrl,
    this.bio,
  });

  final String id;
  final String name;
  final List<String> subjects;
  final double hourlyRate; // PKR per hour for local market
  final String mode; // 'online' | 'physical' | 'hybrid'
  final double rating; // 0..5
  final int numReviews;
  final String? city;
  final double? distanceKm;
  final String? photoUrl;
  final String? bio;
}

final mockTutors = <Tutor>[
  Tutor(
    id: 't1',
    name: 'Sarah Johnson',
    subjects: ['Math', 'Physics'],
    hourlyRate: 5000,
    mode: 'online',
    rating: 4.8,
    numReviews: 112,
    bio: 'STEM specialist with 6+ years of tutoring experience.',
  ),
  Tutor(
    id: 't2',
    name: 'Ahmed Khan',
    subjects: ['Chemistry'],
    hourlyRate: 3000,
    mode: 'physical',
    rating: 4.6,
    numReviews: 64,
    city: 'Lahore',
    distanceKm: 3.2,
    bio: 'Hands-on experiments and easy explanations.',
  ),
  Tutor(
    id: 't3',
    name: 'Emily Chen',
    subjects: ['English', 'IELTS'],
    hourlyRate: 3500,
    mode: 'hybrid',
    rating: 4.9,
    numReviews: 203,
    city: 'Karachi',
    distanceKm: 5.5,
    bio: 'Certified ESL instructor. Focus on speaking and confidence.',
  ),
  Tutor(
    id: 't4',
    name: 'Rohan Patel',
    subjects: ['Computer Science'],
    hourlyRate: 6000,
    mode: 'online',
    rating: 4.7,
    numReviews: 87,
    bio: 'Algorithms, coding interviews, and project mentorship.',
  ),
  Tutor(
    id: 't5',
    name: 'Ayesha Siddiqui',
    subjects: ['Biology'],
    hourlyRate: 2800,
    mode: 'physical',
    rating: 4.5,
    numReviews: 41,
    city: 'Islamabad',
    distanceKm: 2.0,
  ),
  Tutor(
    id: 't6',
    name: 'Hassan Raza',
    subjects: ['Statistics', 'Math'],
    hourlyRate: 4000,
    mode: 'online',
    rating: 4.6,
    numReviews: 72,
  ),
  Tutor(
    id: 't7',
    name: 'Sana Qureshi',
    subjects: ['Accounting', 'Economics'],
    hourlyRate: 3800,
    mode: 'hybrid',
    rating: 4.4,
    numReviews: 55,
    city: 'Karachi',
    distanceKm: 7.1,
  ),
  Tutor(
    id: 't8',
    name: 'Bilal Ahmed',
    subjects: ['Urdu', 'Pak Studies'],
    hourlyRate: 2200,
    mode: 'physical',
    rating: 4.3,
    numReviews: 33,
    city: 'Lahore',
    distanceKm: 4.0,
  ),
  Tutor(
    id: 't9',
    name: 'Zara Ali',
    subjects: ['Islamiyat', 'History'],
    hourlyRate: 2600,
    mode: 'online',
    rating: 4.5,
    numReviews: 61,
  ),
  Tutor(
    id: 't10',
    name: 'Imran Farooq',
    subjects: ['Geography'],
    hourlyRate: 2400,
    mode: 'physical',
    rating: 4.2,
    numReviews: 29,
    city: 'Rawalpindi',
    distanceKm: 6.8,
  ),
  Tutor(
    id: 't11',
    name: 'Mehwish Noor',
    subjects: ['Programming (Flutter)'],
    hourlyRate: 7000,
    mode: 'online',
    rating: 4.8,
    numReviews: 98,
  ),
  Tutor(
    id: 't12',
    name: 'Jawad Iqbal',
    subjects: ['Programming (Java)'],
    hourlyRate: 6500,
    mode: 'online',
    rating: 4.6,
    numReviews: 77,
  ),
  Tutor(
    id: 't13',
    name: 'Fatima Shah',
    subjects: ['Programming (Python)', 'Data Science'],
    hourlyRate: 7500,
    mode: 'hybrid',
    rating: 4.9,
    numReviews: 121,
    city: 'Lahore',
    distanceKm: 8.5,
  ),
  Tutor(
    id: 't14',
    name: 'Ali Abbas',
    subjects: ['Graphic Design'],
    hourlyRate: 5000,
    mode: 'online',
    rating: 4.4,
    numReviews: 45,
  ),
  Tutor(
    id: 't15',
    name: 'Nimra Kareem',
    subjects: ['SAT Prep'],
    hourlyRate: 6000,
    mode: 'online',
    rating: 4.7,
    numReviews: 63,
  ),
  Tutor(
    id: 't16',
    name: 'Omar Saeed',
    subjects: ['GRE Prep'],
    hourlyRate: 6500,
    mode: 'online',
    rating: 4.5,
    numReviews: 52,
  ),
  Tutor(
    id: 't17',
    name: 'Kiran Bashir',
    subjects: ['O/A Levels Prep', 'Math'],
    hourlyRate: 5200,
    mode: 'hybrid',
    rating: 4.8,
    numReviews: 84,
    city: 'Karachi',
    distanceKm: 2.9,
  ),
  Tutor(
    id: 't18',
    name: 'Waqar Ahmed',
    subjects: ['Computer Science', 'Programming (Python)'],
    hourlyRate: 5800,
    mode: 'online',
    rating: 4.6,
    numReviews: 71,
  ),
  Tutor(
    id: 't19',
    name: 'Hiba Anwar',
    subjects: ['English', 'IELTS'],
    hourlyRate: 3900,
    mode: 'physical',
    rating: 4.7,
    numReviews: 66,
    city: 'Islamabad',
    distanceKm: 3.6,
  ),
  Tutor(
    id: 't20',
    name: 'Danish Zafar',
    subjects: ['Statistics', 'Data Science'],
    hourlyRate: 7200,
    mode: 'online',
    rating: 4.5,
    numReviews: 58,
  ),
  Tutor(
    id: 't21',
    name: 'Shahnaz Bibi',
    subjects: ['Sindhi', 'Pak Studies'],
    hourlyRate: 2000,
    mode: 'physical',
    rating: 4.1,
    numReviews: 23,
    city: 'Hyderabad',
    distanceKm: 1.5,
  ),
];


